### ISSUE TITLE
v0.10 fails to build due to missing `lessc.js`

### ISSUE THREAD

**Issue by edwardchapin** [tmtsoftware/icd#23]
I just pulled and attempted to build v0.10 on a CentOS 7.2 Linux machine, and it failed with the following message:

```
$ ./install.sh 
[info] Loading project definition from /home/chapine/source/icd/project
[info] Set current project to root (in build file:/home/chapine/source/icd/)
[info] Set current project to icdWebServer (in build file:/home/chapine/source/icd/)
[info] Wrote /home/chapine/source/icd/icd-web/icd-web-server/target/scala-2.11/icdwebserver_2.11-0.9.pom
[info] Main Scala API documentation to /home/chapine/source/icd/icd-web/icd-web-server/target/scala-2.11/api...
[info] Compiling 8 Scala sources and 1 Java source to /home/chapine/source/icd/icd-web/icd-web-server/target/scala-2.11/classes...
Warning: node.js detection failed, sbt will use the Rhino based Trireme JavaScript engine instead to run JavaScript assets compilation, which in some cases may be orders of magnitude slower than using node.js.
[info] LESS compiling on 1 source(s)
[error] Error: Cannot find module '/home/chapine/source/icd/icd-web/icd-web-server/target/less/lessc.js' (module.js#340)    at module.js:340
[error]     at module.js:280
[error]     at module.js:497
[error]     at startup (trireme.js:142)
[error]     at trireme.js:923
[info] 
model contains 27 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /home/chapine/source/icd/icd-web/icd-web-server/target/scala-2.11/icdwebserver_2.11-0.9-javadoc.jar ...
[info] Done packaging.
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: Error: Cannot find module '/home/chapine/source/icd/icd-web/icd-web-server/target/less/lessc.js' (module.js#340)    at module.js:340
    at module.js:280
    at module.js:497
    at startup (trireme.js:142)
    at trireme.js:923

	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (icdWebServer/web-assets:less) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: Error: Cannot find module '/home/chapine/source/icd/icd-web/icd-web-server/target/less/lessc.js' (module.js#340)    at module.js:340
[error]     at module.js:280
[error]     at module.js:497
[error]     at startup (trireme.js:142)
[error]     at trireme.js:923
[error] Total time: 35 s, completed 18-Feb-2016 9:59:58 AM
```

I then tried to build on an Ubuntu 14.04 system for which earlier versions had worked, and saw the same error.

**Comment by edwardchapin** [comment]
Just a bit of clarification - I stepped backwards through the history and found that the offending commit where this starts happening is abaaf37c6409eba012f20583412322e2732a3d0d

**Comment by abrighton** [comment]
I just tried building icd on CentOS-7.2 in a virtual machine and didn't have any problems.
Does the error happen every time? If you run "sbt clean" first, does that help?

**Comment by edwardchapin** [comment]
Aha! That did it. In both cases I was updating existing builds.
